# Generated by Django 4.2.2 on 2023-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_number_products_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='cart', to='app.products'),
        ),
    ]
